### PR TITLE
Fix parsing from QIODevice

### PR DESCRIPTION
**Pull request by selumin**
[*] Move parsing to private class;
[*] Use same entry point for both parse() API;

### CODE REVIEW

**Comment by selumin** [comment]
When reading from QNetworkReply all data will be read at once. 
It breaks internal logic, please take check following places:https://github.com/flavio/qjson/blob/master/src/json_scanner.cc#L3214,
https://github.com/flavio/qjson/blob/master/src/json_scanner.cpp#L74,
https://github.com/flavio/qjson/blob/master/src/json_scanner.cc#L3983

Will fix https://github.com/flavio/qjson/issues/52

**Comment by flavio** [comment]
I just added travis CI support, could you rebase this PR against master to enable travis runs on this PR?

**Comment by flavio** [comment]
I manually cherry-picked your fixed into master, you did a `merge` instead of a `rebase`. That would have polluted the history of the repo ;)

**Comment by selumin** [comment]
Sorry for this. 
And thanks for help!

**Pull request closed without merging**
